In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing;
from sklearn import model_selection;
from sklearn import linear_model;
from sklearn.model_selection import train_test_split
from sqlalchemy import create_engine
import xgboost as xgb

In [4]:
!pip install xgboost

In [8]:
columns_to_be_removed = ['ra', 'dec']

In [9]:
dataset = pd.read_csv("./training_set.csv").drop(columns_to_be_removed, axis = 'columns') 

In [10]:
dataset.head()

u - g     g - r     r - i     i - z  class
0  0.849407  0.781670  0.651270  0.664084      1
1  0.443531  0.463856  0.484130  0.503074      1
2  0.688782  0.666792  0.588978  0.476186      1
3  0.660274  0.645509  0.550342  0.565342      1
4  0.416464  0.430585  0.472903  0.474130      1

In [11]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
# split data into train and test sets

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

In [13]:
from sklearn.metrics import roc_curve, auc

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

In [14]:
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(X_train, y_train)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


/home/mounica/anaconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:00:51] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 95.24%


In [15]:
from sklearn.metrics import confusion_matrix

print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))

Confusion Matrix: 
 [[2061    1   24]
 [   0  798   37]
 [  63   57  779]]
